### ISSUE TITLE
macOS下打不开 macos10.15 Beta1

### ISSUE THREAD

**Issue by jimtongGH** [haochaco/issue-tracker-zh#103]
<img width="419" alt="屏幕快照2019-06-07下午2 41 16" src="https://user-images.githubusercontent.com/29861276/59085818-6ce7a000-8932-11e9-853c-14a7eb527962.png">

**Comment by jimtongGH** [comment]
不排除可能只是系统问题

**Comment by haochacha** [comment]
请右键任务栏T小图标点击彻底关闭 然后重新打开Tea应该就好了

**Comment by haochacha** [comment]
Duplicate of #104
