### ISSUE TITLE
Macbook Pro OS 10.14.5 JavaScript报错无法启动

### ISSUE THREAD

**Issue by CarlosLiuCN** [haochaco/issue-tracker-zh#104]
![image](https://user-images.githubusercontent.com/46810780/59098487-0626ae80-8953-11e9-89cb-1850385d2074.png)

**Comment by Shadowsong27** [comment]
也遇到了这个问题

**Comment by haochacha** [comment]
请右键任务栏T小图标点击彻底关闭 然后重新打开Tea应该就好了
