### ISSUE TITLE
请问为什么 markdown不支持*** 分段和**加粗啊。。。。

### ISSUE THREAD

**Issue by 1tonsilla** [haochaco/issue-tracker-zh#15]
我不是学代码的
**加粗**，和
*** 
分段可是我为数不多懂的markdown啊，
为啥不支持呢？

**Comment by haochacha** [comment]
感谢反馈！暂时还没有全部支持markdown语法
分段现在我们支持的是 ---
加粗可以通过ctrl/cmd + b或者选中后出现编辑菜单

**Comment by 1tonsilla** [comment]
> 
> 
> 感谢反馈！暂时还没有全部支持markdown语法
> 分段现在我们支持的是 ---
> 加粗可以通过ctrl/cmd + b或者选中后出现编辑菜单

好的**谢谢**您的帮助，希望能够尽快增加双** 的**加粗**功能，因为比较符合舒适的键盘操作，如果使用CTRL+B，相比较起来**不是很好点**，希望以后考虑下能添加吧...

**Comment by moxuanyuan** [comment]
"没有全部支持markdown语法"——tea只支持部分语法所见即所得，但大部分却不支持，造成很混乱的感觉。。。本来手到拿来markdown语法，一输入，却不出结果，实际使用体验很差
