### ISSUE TITLE
在Tea写的.md文章, 导出到csdn上, 一直显示外链图片转存失败

### ISSUE THREAD

**Issue by Ricardo-Charles** [haochaco/issue-tracker-zh#162]
![)@S3}@A 8$7N 5~RC`DH%7](https://user-images.githubusercontent.com/44394716/64073252-b8a9ab80-cccd-11e9-98e9-1b3c37950253.png)
![IPK}G%0{0{)8PV$00S1V(%3](https://user-images.githubusercontent.com/44394716/64073253-c101e680-cccd-11e9-8206-b6fc93fba747.png)

**Comment by MuyuQ** [comment]
你需要图床来存照片.
PC端推荐使用 PicGo来上传图片到图床.
图床推荐微博图床和GitHub图床.

**Comment by zeroTwozeroTwo** [comment]
> 你需要图床来存照片.
> PC端推荐使用 PicGo来上传图片到图床.
> 图床推荐微博图床和GitHub图床.

问一下。是不能使用自己本地的图片嘛？
