### ISSUE TITLE
更换主题报错

### ISSUE THREAD

**Issue by TheresaQWQ** [haochaco/issue-tracker-zh#175]
![TeaBug](https://user-images.githubusercontent.com/22370654/66645115-2fcf4980-ec55-11e9-97bd-8dd75c524331.png)
点击启用就会像上面这样，还有就是 haocha.co 的证书过期了

**Comment by Alecyrus** [comment]
@GouZi2019 建议你试试 [荆棘写作](https://github.com/Greathings-Lab/Thorn-Writing)
