### ISSUE TITLE
编辑时出现冲突文档

### ISSUE THREAD

**Issue by strange-life** [haochaco/issue-tracker-zh#27]
经常在编辑到一半的时候出现冲突文档，同步选择的是 onedrive
<img width="1312" alt="图片" src="https://user-images.githubusercontent.com/19758341/56480875-b6993a00-64ee-11e9-8739-0b0493b30fd8.png">

**Comment by haochacha** [comment]
感谢反馈！OneDrive的话还是建议在fq后使用，不然速度很慢，同步之间会出现冲突。

**Comment by strange-life** [comment]
嗯嗯，之前用 [Joplin](https://github.com/laurent22/joplin) 的时候不会出现这个问题，可能同步策略不一样？但是 tea 的界面比它好看～

**Comment by haochacha** [comment]
感谢！我也去参考一下他们的实现方法。
