### ISSUE TITLE
能否支持 WebDAV?

### ISSUE THREAD

**Issue by chrisxvin** [haochaco/issue-tracker-zh#31]
对不少自己有 Nas 的用户是一大福音啊。
而且我记得坚果云的接口也提供了 WebDAV 的？

**Comment by haochacha** [comment]
感谢反馈，其实坚果云的同步就是通过webdav实现的。我们当时考虑大家可能对webdav不太了解，就放了坚果云的图标。只要点击坚果云输入webdav的信息就是可以使用的了，自己的nas也可以的。
