### ISSUE TITLE
macOS 下速记快捷键无效

### ISSUE THREAD

**Issue by scavin** [haochaco/issue-tracker-zh#4]
[这里介绍](https://meta.appinn.com/t/tea/9828)的速记快捷键 Ctrl + Shift + 空格（command + shift + 空格），并不能在 macOS 下使用，但那个界面的配图又是 macOS，所以目前的速记快捷键是什么？

**Comment by scavin** [comment]
我试出了快捷键是 control shift 空格，但是和原生手写输入法冲突。

**Comment by haochacha** [comment]
恩，谢谢反馈！Tea目前还不支持修改快捷键，之后这个功能会在我们的计划中的。

**Comment by sjtulinhua** [comment]
今天刚装，本想提这个问题结果已经有人提了。这个快捷键很重要啊，并且mac内好像不能修改手写快捷键，只好Tea来改了
