### ISSUE TITLE
markdown原内容编辑

### ISSUE THREAD

**Issue by ddatsh** [haochaco/issue-tracker-zh#6]
从 别处直接复制来的markdown文本，现在没有直接编辑模式

**Comment by haochacha** [comment]
感谢反馈！能不能详细的说一下这个问题呢？是没有渲染出相应的效果吗？

**Comment by ddatsh** [comment]
typora 的 ctrl+/ ，切换markdown实时渲染和原文编辑的功能

比如 从 typora 等复制过来的 markdown 源文件

就没有个直接能在 tea  编辑修改的功能了。。。。
