### ISSUE TITLE
与坚果云同步时非常卡，卡到死机，再次打开应用所有markdown文件全没了

### ISSUE THREAD

**Issue by LiamCodesX** [haochaco/issue-tracker-zh#70]
能否说明下tea的默认存储位置，花费一天写的文档没了很心疼，使用everything搜索还是没能找到文档，怀疑文档被删除了

**Comment by LiamCodesX** [comment]
![image](https://user-images.githubusercontent.com/34621898/56666618-d8591380-66de-11e9-8ff5-f564b54c27d4.png)
卡完后，内存占用到了23个G，我写的文档最多1M

**Comment by LiamCodesX** [comment]
我现在想恢复数据，请看到后回复我，数据存储位置，文档对我来说很重要！！！

**Comment by haochacha** [comment]
已与用户微信联系。
